version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=appocation
      - MONGODB_INITDB_ROOT_PASSWORD=any_pass
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=appocation
      - MONGO_INITDB_ROOT_PASSWORD=any_pass
    volumes:
      - vol_name:/data/db
volumes:
  vol_name:
